---
- name: Run traceroute commands
  hosts: cisco-routers
  gather_facts: false
  remote_user: cisco

  vars:
    loopbacks: {
    "csrv1": "10.1.1.1",
    "csrv2": "10.2.1.1",
    "csrv3": "10.3.1.1",
    "csrv4": "10.4.1.1",
    }

  tasks:

    - name: run traceroute to every other host
      raw: traceroute {{ item.value }} source Loopback0 probe 1 numeric
      when: item.key != inventory_hostname
      with_dict: loopbacks
      register: trace_result

#    - name: Debug registered variables
#      debug: var=trace_result
