---
- name: Configure with Template
  hosts: csrv4
  

  tasks:
    - ios_command:
        username: cisco
        password: cisco
        commands: show running-config 
        authorize: yes
        auth_pass: cisco
      register: result
    - debug: var=result 
