---
- name: Configure with Template
  hosts: csrv4
  connection: local

  tasks:
    - ios_config:
        username: cisco
        password: cisco
        commands: "{{lookup('file', 'test.txt')}}"
        backup: yes
        authorize: yes
        auth_pass: cisco
  
