---
- name: Configure with Template
  hosts: csrv4
  connection: local
  

  tasks:
    - ios_command:
        username: cisco
        password: cisco
        commands: "{{lookup('file', 'text1.txt')}}" 
        authorize: yes
        auth_pass: cisco
      register: result
    - debug: var=result 
