---
- name: Configure with Template
  hosts: csrv1
  connection: local

  tasks:
    - ios_template:
        username: cisco
        password: cisco
        src: configtemp.txt
        backup: yes
  
