---
- name: Configure with Template
  hosts: csrv4

  tasks:
    - ios_config:
        username: cisco
        password: cisco
        commands: "{{lookup('file', 'test.txt')}}"
        backup: yes
  
