
---
- name: Configure Interface
  hosts: csrv3
  tasks:
    - ios_config:
        lines: 
          - network 0.0.0.0 mask 255.255.255.255
          - neighbor 172.16.1.12 remote-as 100
          - neighbor 172.16.1.12 remote-as self
          - neighbor 172.16.1.12 next-hop-self
        parents: router bgp 200
        username: cisco
        password: cisco
        authorize: yes
        auth_pass: cisco

