
---
- name: Configure Interface
  hosts: csrv3
  tasks:
    - ios_config:
        lines: 
          - "'network 0.0.0.0 mask 255.255.255.255'"
        parents: router bgp 200
        username: cisco
        password: cisco
        authorize: yes
        auth_pass: cisco

