
---
- name: Configure Interface
  hosts: csrv1
  tasks:
    - ios_config:
        lines: 
          - description test interface
        parents: interface GigabitEthernet4
        username: cisco
        password: cisco

