
---
- name: Configure Interface
  hosts: csrv1
  tasks:
    - ios_config:
        lines: 
          - network 172.16.2.0 0.255.255.255
        parents: router ospf 260
        username: cisco
        password: cisco
        authorize: yes
        auth_pass: cisco

