
---
- name: Configure Interface
  hosts: cisco-csrv
  tasks:
    - ios_config:
        lines: 
          - network 0.0.0.0 255.255.255.255 area 0
        parents: router ospf 270
        username: cisco
        password: cisco
        authorize: yes
        auth_pass: cisco

