
---
- name: Configure Interface
  hosts: csrv1
  tasks:
    - ios_config:
        lines: 
          - network 0.0.0.0 255.255.255.255 area 0
        parents: router ospf 260
        username: cisco
        password: cisco
        authorize: yes
        auth_pass: cisco

